project:
  type: website
  output-dir: docs

website:
  title: "ENZIE.STAT244.github.io"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - href: test.qmd
        text: STAT-244 (bird-version)

format:
  html:
    theme: minty
    mainfont: arial
    fontsize: 1.5rem
    fontcolor: "#B5D268"
    linkcolor: "#E2FD9E"
    monofont: courier new
    toc: true

editor: visual

